const catalog=[
{name:'Finikoudes',categories:['waterfront','walk'],lat:34.914,lng:33.6384,copy:{en:'Palm-lined waterfront and a practical starting point for the centre.',ru:'Набережная с пальмами и удобная отправная точка для центра.',el:'Παραλιακό μέτωπο με φοίνικες και εύκολη αφετηρία για το κέντρο.',he:'טיילת עם דקלים ונקודת התחלה נוחה למרכז.'}},
{name:'Church of Saint Lazarus',categories:['heritage','old-town'],lat:34.9121,lng:33.6341,copy:{en:'Historic landmark near the old-town streets.',ru:'Историческая достопримечательность рядом с улицами старого города.',el:'Ιστορικό μνημείο κοντά στους δρόμους της παλιάς πόλης.',he:'אתר היסטורי ליד רחובות העיר העתיקה.'}},
{name:'Larnaca Medieval Castle',categories:['heritage','waterfront'],lat:34.9087,lng:33.6375,copy:{en:'Fort area at the southern end of the promenade.',ru:'Район форта в южной части набережной.',el:'Περιοχή φρουρίου στο νότιο άκρο του παραλιακού δρόμου.',he:'אזור המצודה בקצה הדרומי של הטיילת.'}},
{name:'Kition Archaeological Site',categories:['heritage','history'],lat:34.923,lng:33.6305,copy:{en:'An archaeological context for ancient Larnaca.',ru:'Археологический контекст древней Ларнаки.',el:'Αρχαιολογικό πλαίσιο για την αρχαία Λάρνακα.',he:'הקשר ארכאולוגי ללרנקה העתיקה.'}},
{name:'Larnaca Salt Lake',categories:['nature','walk'],lat:34.894,lng:33.6145,copy:{en:'A separate nature stop; check current access before going.',ru:'Отдельная природная остановка; проверьте доступ перед поездкой.',el:'Ξεχωριστή φυσική στάση· ελέγξτε την πρόσβαση πριν πάτε.',he:'עצירת טבע נפרדת; בדקו את הגישה לפני היציאה.'}},
{name:'Municipal Historical Archives–Museum',categories:['history','heritage'],lat:34.9154,lng:33.6356,copy:{en:'Municipal museum at Europe Square with city-history collections; confirm visiting times.',ru:'Муниципальный музей на площади Европы с материалами по истории города; уточните часы работы.',el:'Δημοτικό μουσείο στην Πλατεία Ευρώπης με συλλογές για την ιστορία της πόλης.',he:'מוזיאון עירוני בכיכר אירופה עם אוספים על תולדות העיר.'}},
{name:'Municipal Art Gallery',categories:['art','heritage'],lat:34.9158,lng:33.6361,copy:{en:'Municipal gallery area near Europe Square; exhibitions change.',ru:'Район муниципальной галереи у площади Европы; выставки меняются.',el:'Περιοχή της Δημοτικής Πινακοθήκης κοντά στην Πλατεία Ευρώπης.',he:'אזור הגלריה העירונית סמוך לכיכר אירופה.'}},
{name:'Kamares Aqueduct',categories:['heritage','walk'],lat:34.8967,lng:33.6098,copy:{en:'Historic aqueduct area, suited to combine with the salt-lake route.',ru:'Исторический акведук, который удобно совместить с маршрутом у солёного озера.',el:'Ιστορικό υδραγωγείο, κατάλληλο να συνδυαστεί με τη διαδρομή της αλυκής.',he:'אמת מים היסטורית, מתאימה לשילוב עם מסלול אגם המלח.'}},
{name:'Mackenzie Waterfront',categories:['waterfront','food'],lat:34.886,lng:33.616,copy:{en:'Seafront area for a beach walk or evening pause; check venues directly.',ru:'Район у моря для пляжной прогулки или вечерней паузы; проверяйте заведения напрямую.',el:'Παραλιακή περιοχή για βόλτα στην παραλία ή βραδινή στάση.',he:'אזור חוף להליכה או לעצירת ערב; בדקו את המקומות ישירות.'}},
{name:'Hala Sultan Tekke',categories:['heritage','nature'],lat:34.8795,lng:33.6065,copy:{en:'Important religious site beside the salt lake; respect site rules and check access.',ru:'Важный религиозный объект у солёного озера; соблюдайте правила и проверьте доступ.',el:'Σημαντικός θρησκευτικός χώρος δίπλα στην αλυκή· ελέγξτε πρόσβαση και κανόνες.',he:'אתר דתי חשוב ליד אגם המלח; כבדו את הכללים ובדקו גישה.'}},{name:'Mackenzie Beach',categories:['beach','waterfront','food'],lat:34.8879,lng:33.6178,copy:{en:'A wide sandy beach with a promenade, cafés and evening views.',ru:'Широкий песчаный пляж с променадом, кафе и вечерними видами.',el:'Μεγάλη αμμώδης παραλία με πεζόδρομο, καφέ και βραδινή θέα.',he:'חוף חולי רחב עם טיילת, בתי קפה ונופי ערב.'}}
,{name:'Kastella Beach',categories:['beach','waterfront','family'],lat:34.9007,lng:33.6370,copy:{en:'Small city beach near the fishing harbour, suitable for a relaxed swim stop.',ru:'Небольшой городской пляж у рыбацкой гавани для спокойной остановки и купания.',el:'Μικρή παραλία πόλης κοντά στο αλιευτικό καταφύγιο, για χαλαρή στάση για μπάνιο.',he:'חוף עירוני קטן ליד נמל הדיג, מתאים לעצירת שחייה רגועה.'}}
,{name:'CTO Beach',categories:['beach','family','nature'],lat:34.9705,lng:33.6745,copy:{en:'Sandy beach in the Dhekelia area, useful for a longer beach day.',ru:'Песчаный пляж в районе Декелия для более долгого дня у моря.',el:'Αμμώδης παραλία στην περιοχή Δεκέλεια, καλή για μεγαλύτερη μέρα στη θάλασσα.',he:'חוף חולי באזור דקליה, מתאים ליום ארוך יותר בים.'}}
];
const ui={en:{search:'Search',placeholder:'Search places, history, waterfront…',all:'All',waterfront:'Waterfront',heritage:'Heritage',history:'History',art:'Art',food:'Food',nature:'Nature',walk:'Walks',beach:'Beaches',oldTown:'Old town',found:'places found',directions:'Directions'},ru:{search:'Найти',placeholder:'Найти место, историю, набережную…',all:'Все',waterfront:'Набережная',heritage:'Наследие',history:'История',art:'Искусство',food:'Еда',nature:'Природа',walk:'Прогулки',beach:'Пляжи',oldTown:'Старый город',found:'мест найдено',directions:'Маршрут'},el:{search:'Αναζήτηση',placeholder:'Αναζήτηση τοποθεσιών, ιστορίας, ακτής…',all:'Όλα',waterfront:'Παραλία',heritage:'Κληρονομιά',history:'Ιστορία',art:'Τέχνη',food:'Φαγητό',nature:'Φύση',walk:'Βόλτες',beach:'Παραλίες',oldTown:'Παλιά πόλη',found:'αποτελέσματα',directions:'Διαδρομή'},he:{search:'חיפוש',placeholder:'חיפוש מקומות, היסטוריה, טיילת…',all:'הכול',waterfront:'טיילת',heritage:'מורשת',history:'היסטוריה',art:'אמנות',food:'אוכל',nature:'טבע',walk:'מסלולים',beach:'חופים',oldTown:'עיר עתיקה',found:'מקומות נמצאו',directions:'מסלול'}};
const localNames={Finikoudes:{ru:'Финикудес',el:'Φοινικούδες',he:'פיניקודס'},'Church of Saint Lazarus':{ru:'Церковь Святого Лазаря',el:'Εκκλησία Αγίου Λαζάρου',he:'כנסיית לזרוס הקדוש'},'Larnaca Medieval Castle':{ru:'Средневековый замок Ларнаки',el:'Μεσαιωνικό Κάστρο Λάρνακας',he:'המצודה הימי-ביניימית של לרנקה'},'Kition Archaeological Site':{ru:'Археологический объект Китион',el:'Αρχαιολογικός Χώρος Κιτίου',he:'האתר הארכאולוגי קיטיון'},'Larnaca Salt Lake':{ru:'Солёное озеро Ларнаки',el:'Αλυκή Λάρνακας',he:'אגם המלח של לרנקה'}};
const aliases={'Finikoudes':'финикудес финекудес promenade','Church of Saint Lazarus':'лазарь лазаря church','Larnaca Medieval Castle':'замок форт castle','Kition Archaeological Site':'китион китий kition archaeology','Larnaca Salt Lake':'озеро солёное соленое алики salt lake','Municipal Historical Archives–Museum':'архив музей европы','Municipal Art Gallery':'галерея искусство','Kamares Aqueduct':'камарес акведук','Mackenzie Waterfront':'маккензи пляж','Mackenzie Beach':'маккензи пляж','Kastella Beach':'кастелла пляж','CTO Beach':'сто декелия пляж','Hala Sultan Tekke':'хала султан текке мечеть'};
Object.assign(localNames,{'Municipal Historical Archives–Museum':{ru:'Муниципальный исторический архив-музей',el:'Δημοτικό Ιστορικό Αρχείο–Μουσείο',he:'המוזיאון והארכיון ההיסטורי העירוני'},'Municipal Art Gallery':{ru:'Муниципальная художественная галерея',el:'Δημοτική Πινακοθήκη',he:'הגלריה העירונית'},'Kamares Aqueduct':{ru:'Акведук Камарес',el:'Υδραγωγείο Καμάρες',he:'אמת המים קמארס'},'Mackenzie Waterfront':{ru:'Набережная Маккензи',el:'Παραλία Μακένζι',he:'טיילת מקנזי'},'Hala Sultan Tekke':{ru:'Хала Султан Текке',el:'Χαλά Σουλτάν Τεκκέ',he:'האלה סולטאן טקה'},'Mackenzie Beach':{ru:'Пляж Маккензи',el:'Παραλία Μακένζι',he:'חוף מקנזי'},'Kastella Beach':{ru:'Пляж Кастелла',el:'Παραλία Καστέλλα',he:'חוף קסטלה'},'CTO Beach':{ru:'Пляж CTO, Декелия',el:'Παραλία CTO, Δεκέλεια',he:'חוף CTO, דקליה'}});
let category='all',query='';const keys=['all','beach','waterfront','heritage','history','art','food','nature','walk','oldTown'];const dirSearch=(lat,lng)=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(lat+','+lng)}&travelmode=driving`;
function renderSearch(){const lang=document.documentElement.lang||'en',t=ui[lang]||ui.en,filters=document.querySelector('#search-filters'),list=document.querySelector('#place-list'),summary=document.querySelector('#result-summary'),input=document.querySelector('#place-search'),button=document.querySelector('#search-button');if(!filters)return;input.placeholder=t.placeholder;button.textContent=t.search;filters.innerHTML='';keys.forEach(key=>{const b=document.createElement('button');b.className='filter'+(category===key?' active':'');b.textContent=t[key];b.type='button';b.onclick=()=>{category=key;renderSearch()};filters.append(b)});const q=query.trim().toLocaleLowerCase(),wanted=category==='oldTown'?'old-town':category;const matches=catalog.filter(item=>(category==='all'||item.categories.includes(wanted))&&(!q||[item.name,item.copy.en,item.copy.ru,item.copy.el,item.copy.he,aliases[item.name],...item.categories].join(' ').toLocaleLowerCase().includes(q)));const russianEnding=matches.length%10===1&&matches.length%100!==11?'место':matches.length%10>=2&&matches.length%10<=4&&(matches.length%100<10||matches.length%100>=20)?'места':'мест';summary.textContent=lang==='ru'?`${matches.length} ${russianEnding} найдено`:`${matches.length} ${t.found}`;list.innerHTML='';matches.forEach(item=>{const card=document.createElement('a');card.className='place-card';card.href=dirSearch(item.lat,item.lng);card.target='_blank';card.rel='noopener';card.innerHTML=`<b>${localNames[item.name]?.[lang]||item.name}</b><em>${item.copy[lang]||item.copy.en}</em><small>${t.directions} ↗</small>`;card.onmouseenter=()=>map.setView([item.lat,item.lng],15,{animate:true});list.append(card)});}
const beforeSearchLanguage=setLanguage;setLanguage=function(lang){beforeSearchLanguage(lang);renderSearch()};document.querySelector('#place-search').addEventListener('input',event=>{query=event.target.value;renderSearch()});document.querySelector('#search-button').onclick=()=>{document.querySelector('#map').scrollIntoView({behavior:'smooth'});renderSearch()};renderSearch();
